; This file was auto-generated by drush make and customized by ewb - Summer 2012
core = 7.x

api = 2
projects[] = "drupal"


; Modules
projects[advanced_help][subdir] = "contrib"

projects[backup_migrate][subdir] = "contrib"

projects[boxes][subdir] = "contrib"

projects[calendar][subdir] = "contrib"

projects[colorbox][subdir] = "contrib"

projects[context][subdir] = "contrib"

projects[ctools][subdir] = "contrib"

projects[date][subdir] = "contrib"

projects[devel][subdir] = "contrib"

projects[diff][subdir] = "contrib"

projects[entity][subdir] = "contrib"

projects[entitycache][subdir] = "contrib"

projects[entityreference][subdir] = "contrib"

projects[environment_indicator][subdir] = "contrib"

projects[features][subdir] = "contrib"

projects[feeds][subdir] = "contrib"

projects[field_group][subdir] = "contrib"

projects[google_analytics][subdir] = "contrib"

projects[libraries][subdir] = "contrib"

projects[imagefield_crop][subdir] = "contrib"

projects[link][subdir] = "contrib"

projects[omega_tools][subdir] = "contrib"

projects[panels][subdir] = "contrib"

projects[pathauto][subdir] = "contrib"

projects[rules][subdir] = "contrib"

projects[strongarm][subdir] = "contrib"

projects[token][subdir] = "contrib"

projects[views][subdir] = "contrib"

projects[webform][subdir] = "contrib"

projects[wysiwyg][subdir] = "contrib"

projects[xmlsitemap][subdir] = "contrib"




; Themes
projects[] = "omega"
projects[] = "beta"


; Libraries
libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.6.3/ckeditor_3.6.3.tar.gz"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

libraries[colorbox][download][type] = "get"
libraries[colorbox][download][url] = "http://colorpowered.com/colorbox/colorbox.zip"
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][destination] = "libraries"


